default:
  image_source_directory: /Volumes/EOS_DIGITAL
  image_destination_directory: /Volumes/CapsuleDrive/created/images/imported
  image_extensions:
  - .JPG
  - .CR2
  destination_file_name: ":ext/:date/:original_name"
